import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import Providers from "@/src/providers/PrivyProvider";
import { AppProvider } from "@/src/providers/AppProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PolyMarket | CopyTrading",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-y-scroll no-scrollbar">
      <body className="min-h-screen">
        <Providers>
  
          <AppProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}